<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE BipMenu [
	<!ELEMENT BipMenu (menus,infos,items,filters)>
	
	<!ELEMENT menus (menu*)>
	<!ATTLIST menus
		defaultBackGroundColor CDATA #IMPLIED
	>
	
	<!ELEMENT menu (menuInfo*, menuItem*)>
	<!ATTLIST menu
		id		IDREF	#REQUIRED
		backGroundColor CDATA #IMPLIED
	>
	
	<!ELEMENT menuInfo EMPTY>
	<!ATTLIST menuInfo
		id IDREF	#REQUIRED
	>
	
	<!ELEMENT menuItem ( (filter_and | filter_or | filter_field | filter_other | filter_id)? , menuItem*)>
	<!ATTLIST menuItem
		id IDREF	#REQUIRED
	>
	
	<!ELEMENT filter_and ((filter_and*, filter_or*, filter_field*, filter_id*, filter_other*)*)>
	<!ATTLIST filter_and
		not (true|false) "false"
	>
	
	<!ELEMENT filter_or  ((filter_and*, filter_or*, filter_field*, filter_id*, filter_other*)*)>
	<!ATTLIST filter_or
		not (true|false) "false"
	>
	
	<!ELEMENT filter_field EMPTY>
	<!ATTLIST filter_field
		not (true|false) "false"
		fieldName CDATA #REQUIRED
		validValues CDATA #REQUIRED
	>
	
	<!ELEMENT filter_other EMPTY>
	<!ATTLIST filter_other
		not (true|false) "false"
		className CDATA #REQUIRED
		functionName CDATA	#REQUIRED
	>
	
	<!ELEMENT filter_id EMPTY>
	<!ATTLIST filter_id
		not (true|false) "false"
		id IDREF #REQUIRED
	>
	
	
	<!ELEMENT items (item*)>
	<!ATTLIST items
		defaultHelpPage		CDATA	#REQUIRED
		defaultFilterId	CDATA	#REQUIRED
	>
	
	<!ELEMENT item	(#PCDATA)>
	<!ATTLIST item
		id	ID	#REQUIRED
		label	CDATA	#REQUIRED
		altLabel	CDATA	#IMPLIED
		link	CDATA	#IMPLIED
		linkOptions	CDATA #IMPLIED
		helpPage	CDATA #IMPLIED
		filterId	CDATA #IMPLIED
	>
	
	<!ELEMENT infos (info*)>
	
	<!ELEMENT info EMPTY>
	<!ATTLIST info
		id	ID	#REQUIRED
		className CDATA #REQUIRED
		functionName CDATA	#REQUIRED
	>
	
	<!ELEMENT filters (filter*)>
	
	<!ELEMENT filter (filter_and | filter_or | filter_field | filter_other)>
	<!ATTLIST filter
		id	ID	#REQUIRED
	>
]>

<!--
	Gestion des apostrophes dans les altLabel (info bulle) :
	on genere le & par &amp;
	puis on met rsquo; qui correspond a une quote fermante
	*******************************************************************************************************************************
-->

<BipMenu>
	<menus defaultBackGroundColor="#DDDDFF">

		<!--
			*******************************************************************************************************************************
			NOUVEAUX MENUS
			*******************************************************************************************************************************
		-->

		<!--	Menu Adminstration -->

		<!--    ATTENTION : Le nom des menus de premier niveau doit être en MAJUSCULES -->

		<menu id="DIR">
			<menuItem id="Favoris" />
			<menuItem id="Table">
			<!-- KRA 64733 -->
			<filter_field not="true" fieldName="SousMenus" validValues="admbase"/>
				<menuItem id="ssMAJTable">
					<filter_field fieldName="SousMenus"
						validValues="admin" />
					<menuItem id="majDPG" />
					<menuItem id="majClients" />
					<menuItem id="majSocietes" />
					<menuItem id="majCAMO" />
					<menuItem id="majPrestations" />
					<menuItem id="majStandards" />
					<menuItem id="majProfilFi" />
					<menuItem id="majProfilDomFonc" />
					<!-- Start of Profils Localisés Menu -->
					<menuItem id="majProfileLoc" />
					<!-- End of Profils Localisés Menu -->
					<menuItem id="majCoutMoyenComplet" />
					<menuItem id="majImmeubles" />
					<menuItem id="majType1" />
					<menuItem id="majType2" />
					<menuItem id="majSousType" />
					<menuItem id="majProjetsSpeciaux" />
					<menuItem id="majFiliales" />
					<menuItem id="majCompta" />
					<menuItem id="majCentre2Frais" />
					<menuItem id="majTxAnnuels" />
					<menuItem id="majInvestissements" />
					<menuItem id="majPoste" />
					<menuItem id="majNature" />
					<menuItem id="majSousSysteme" />
					<menuItem id="majDomaine" />
					<menuItem id="majBloc" />
					<menuItem id="majCompte" />
					<menuItem id="majRubrique" />
					<menuItem id="majBranches" />
					<menuItem id="majDirections" />
					<!-- YNI -->
					<menuItem id="majDateEffet" />
					<menuItem id="majLocalisation" />
					<menuItem id="majContractuel" />
					<menuItem id="majTraitement" />
					<menuItem id="majTypeEtape" />
					<!-- Fin YNI -->
				</menuItem>
				<menuItem id="ssEdTable">
				<!-- KRA 64733 -->
					<filter_field not="true" fieldName="SousMenus" validValues="admbase"/>
					<menuItem id="eTableDPG" />
					<menuItem id="eTableClients" />
					<menuItem id="eTableSocietes" />
					<menuItem id="eTablePrestations" />
					<menuItem id="eModeContractuel" />
					<menuItem id="eTableStandards" />
					<menuItem id="eProfilsFi" />
					<menuItem id="eProfilsDomFonc" />
					<!-- New Edition report for Profile localize - Starts -->
					<menuItem id="eProfilsLocalize" />
					<!-- New Edition report for Profile localize - Ends -->
					<menuItem id="eTableCoutMoyenComplet" />
					<menuItem id="eTableImmeubles" />
					<menuItem id="eTableInvestissements" />
					<menuItem id="eTableTypesProjet" />
					<menuItem id="eTableCompta" />
					<menuItem id="eTableProjets" />
					<menuItem id="eTableApplications" />
					<menuItem id="eTableDossiersProjet" />
					<menuItem id="eTableCentre2Frais" />
					<menuItem id="eRubriques" />
					<menuItem id="eDirections" />
					<menuItem id="eParamBip" />
					<menuItem id="eTypeEtape" />
				</menuItem>
			</menuItem>
			<menuItem id="Referentiels">
			<!-- KRA 64733 -->
				<filter_field not="true" fieldName="SousMenus" validValues="admbase"/>
				<menuItem id="majProjet">
				<filter_field fieldName="SousMenus" validValues="admin"/>
				</menuItem>
				<menuItem id="majApplications">
				<filter_field fieldName="SousMenus" validValues="admin"/>
				</menuItem>
				<menuItem id="majDossierProjet">
				<filter_field fieldName="SousMenus" validValues="admin"/>
				</menuItem>
				<!-- TD 532 -->
				<!-- menuItem id="majLienDPDomBancaire"/-->
				<!-- TD 532 -->
				<menuItem id="ssEdRef">
				<!-- KRA 64733 -->
					<filter_field not="true" fieldName="SousMenus" validValues="admbase"/>
					<menuItem id="eRef" />
					<menuItem id="eRefProj" />
					<menuItem id="ePCA4" />
					<menuItem id="eSuiviType1" />
					<menuItem id="eProjetsSpeciaux" />
				</menuItem>
				<!-- TD 532 -->
				<menuItem id="ssExportRef">
					<filter_field fieldName="SousMenus"
						validValues="admin" />
					<menuItem id="xDossierProjet" />
					<menuItem id="ssXProjet">
						<menuItem id="xProjet" />
						<menuItem id="xProjet2" />
						<menuItem id="xProjet3" />
						<menuItem id="xProjet4" />
						<menuItem id="xProjet5" />
						<menuItem id="xProjet6" />
					</menuItem>
					<menuItem id="xApplication" />
					<menuItem id="xLiensProjetsCA" />
					<menuItem id="xLiensApplicationsCA" />
					<menuItem id="xDephasagesCAlignesCAprojetsapplic" />
					<menuItem id="xProjetVersDEVL" />
				</menuItem>
				<!-- TD 532 -->
			</menuItem>
			<menuItem id="Copi">
				<filter_field fieldName="SousMenus" validValues="copi" />
				<menuItem id="ssMAJTable">
					<menuItem id="BudgetCopiP">
						<menuItem id="CreationCopi" />
						<menuItem id="ModifSuppCopi" />
						<menuItem id="MajMasseCopiP" />
						<menuItem id="ValidMasseCopiP" />
					</menuItem>
					<menuItem id="BudgetCopiNP">
						<menuItem id="MajMasseCopiNP" />
					</menuItem>
					<menuItem id="ExceptionCopi" />
					<menuItem id="DateCopi" />
					<menuItem id="DpCopi" />
					<menuItem id="FourCopi" />
					<menuItem id="NotationCopi" />
					<menuItem id="AxeStrategiqueCopi" />
					<menuItem id="EtapesCopi" />
					<menuItem id="ValidationDpCopi" />
				</menuItem>
				<menuItem id="ssEdTable">
					<menuItem id="eExceptionCopi" />
					<menuItem id="eDateCopi" />
					<menuItem id="eDpCopi" />
					<menuItem id="eFourCopi" />
				</menuItem>
				<menuItem id="SuiviCopi">
					<filter_field fieldName="SousMenus"
						validValues="copi" />
				</menuItem>
				<!-- YNI FDT 798 -->
				<menuItem id="LogDpCopi">
					<filter_field fieldName="SousMenus"
						validValues="copi" />
				</menuItem>
				<menuItem id="LogBudgetCopi">
					<filter_field fieldName="SousMenus"
						validValues="copi" />
				</menuItem>
				<!-- Fin YNI FDT 798 -->
			</menuItem>
			<menuItem id="Ressources">
				<filter_field fieldName="SousMenus" validValues="admin" />
				<menuItem id="ssEdRess">
					<menuItem id="eRessources" />
					<menuItem id="eListeTel" />
					<menuItem id="eSuiviSSII" />
					<menuItem id="eSuiviPrestations" />
					<menuItem id="eContratsEchus" />
					<menuItem id="eRessOrdreAlpha" />
					<menuItem id="eRessCodeRess" />
					<!--  menuItem id="eOrganisation"/ -->
					<menuItem id="eDetailAbsSG" />
					<menuItem id="eSyntheseAbsSG" />
					<menuItem id="eEcarts" />					
				</menuItem>
				<!-- menuItem id="detailMe"/-->
				<menuItem id="Consultation" />
				<menuItem id="ssMAJRess">
					<menuItem id="majAgentSG" />
					<menuItem id="majPrestataires" />
					<menuItem id="majLogiciels" />
					<menuItem id="majForfaits" />
				</menuItem>
				<menuItem id="ssBouclageRess">
					<menuItem id="bjhValidErreurs" />
					<menuItem id="eBjh" />
					<menuItem id="majTypeAbs" />
				</menuItem>
				<menuItem id="majEcarts" />
				<menuItem id="eSyntheseGlobaleMe" />
			</menuItem>
			<menuItem id="LigneBIP">
				<filter_field fieldName="SousMenus" validValues="admin" />
				<menuItem id="majLigneBip" />
				<menuItem id="majMultiCA" />
				<menuItem id="ssEdLigneBip">
					<menuItem id="eLigneBipFiche" />
					<menuItem id="xLigneBipAd" />
					<menuItem id="eLigneBipSSTrait" />
					<menuItem id="eMultiCA" />
					<menuItem id="eTableRepart" />
				</menuItem>
				<menuItem id="ssLiensLigneBip">
					<menuItem id="majLienDP" />
					<menuItem id="majLienDPG" />
					<menuItem id="majLienMO" />
					<menuItem id="majLienCAMO" />
					<menuItem id="majLienProjet" />
					<menuItem id="majLienApp" />
					<menuItem id="majLienCpBIP" />
				</menuItem>
				<menuItem id="ssRJHLigneBip">
					<menuItem id="majTableRepart" />
					<menuItem id="majLoadTableRepart" />
					<!-- menuItem id="majLoadLigneBip"/ -->
					<menuItem id="vRapportTableRepart" />
					<!-- menuItem id="majProposesTableRepart"/-->
					<!-- menuItem id="majArbitresTableRepart"/-->
					<menuItem id="eLogAlimConsoRepart" />
				</menuItem>
			</menuItem>
			<menuItem id="BudgetJH">
			<filter_field fieldName="SousMenus" validValues="admin admbase"/>
				<menuItem id="majNotificationBudjet">
				<!-- KRA 64733 -->
					<filter_field not="true" fieldName="SousMenus" validValues="admbase"/>
				</menuItem>
				<menuItem id="ssParLigneBujetJH">
				<!-- KRA 64733 -->
					<filter_field not="true" fieldName="SousMenus" validValues="admbase"/>
					<menuItem id="majBudjetJH" />
					<menuItem id="majPropose" />
					<menuItem id="majReestime" />
				</menuItem>
				<!-- menuItem id="majBudActJh"/-->
				<menuItem id="ssSaisieMasse">
				<!-- KRA 64733 -->
					<filter_field not="true" fieldName="SousMenus" validValues="admbase"/>
					<menuItem id="majBudgetMesLignes" />
					<menuItem id="majBudgetLignesMO" />
				</menuItem>
				<menuItem id="editionBudJh">
				<!-- KRA 64733 -->
					<filter_field not="true" fieldName="SousMenus" validValues="admbase"/>
					<!-- menuItem id="eSuiviMensuelG"/-->
					<menuItem id="eSuiviMensuel" />
					<menuItem id="xEcartsBudgets" />
					<menuItem id="xPIDValide" />
				</menuItem>
				<menuItem id="majEcartsBudgets">
				<!-- KRA 64733 -->
					<filter_field not="true" fieldName="SousMenus" validValues="admbase"/>
				</menuItem>
				<menuItem id="majArbitrageLignes">
				<filter_field fieldName="SousMenus" validValues="admin admbase"/>
				</menuItem>				
			</menuItem>
			<menuItem id="EditionsAd">
				<filter_field fieldName="SousMenus" validValues="admin" />
				<menuItem id="eRapprochement" />
				<menuItem id="xLigneFact" />
			</menuItem>
			<menuItem id="Export">
				<filter_field fieldName="SousMenus" validValues="admin admbase" /> <!-- KRA 64733 -->
				<menuItem id="xLigneBip">
				<!-- KRA 64733 -->
					<filter_field not="true" fieldName="SousMenus" validValues="admbase"/>
				</menuItem>
				<menuItem id="xLigneBipAct">
				<!-- KRA 64733 -->
					<filter_field not="true" fieldName="SousMenus" validValues="admbase"/>
				</menuItem>
				<menuItem id="xOriSaisieConso">
				<!-- KRA 64733 -->
					<filter_field not="true" fieldName="SousMenus" validValues="admbase"/>
				</menuItem>
				<menuItem id="xRessMois">
				<!-- KRA 64733 -->
					<filter_field not="true" fieldName="SousMenus" validValues="admbase"/>
				</menuItem>
				<menuItem id="xPersonne">
				<!-- KRA 64733 -->
					<filter_field not="true" fieldName="SousMenus" validValues="admbase"/>
				</menuItem>
				<!-- TD 532 -->
				<!-- menuItem id="xDossierProjet"/-->
				<!-- menuItem id="ssXProjet">
					<menuItem id="xProjet"/>
					<menuItem id="xProjet2"/>
					<menuItem id="xProjet3"/>
					<menuItem id="xProjet4"/>
					<menuItem id="xProjet5"/>
					<menuItem id="xProjet6"/>			        
					</menuItem-->
				<!-- menuItem id="xApplication"/-->
				<!-- TD 532 -->
				<menuItem id="xRessActive">
				<!-- KRA 64733 -->
					<filter_field not="true" fieldName="SousMenus" validValues="admbase"/>
				</menuItem>
				<menuItem id="eEcartsCons">
				<!-- KRA 64733 -->
					<filter_field not="true" fieldName="SousMenus" validValues="admbase"/>
				</menuItem>
				<menuItem id="ssXEBis">
				<!-- KRA 64733 -->
					<filter_field not="true" fieldName="SousMenus" validValues="admbase"/>
					<menuItem id="xLogsContratsEbis" />
					<menuItem id="xLogsFacturesEbis" />
					<menuItem id="xLogsTTEbis" />
					<menuItem id="xLogsLigneContEbis" />
				</menuItem>
				<menuItem id="xDPG" />

				<menuItem id="xMO" />				
				<menuItem id="xAuditFonct">
				<!-- KRA 64733 -->
					<filter_field not="true" fieldName="SousMenus" validValues="admbase"/>
				</menuItem>
				<menuItem id="xStockFI">
				<!-- KRA 64733 -->
					<filter_field not="true" fieldName="SousMenus" validValues="admbase"/>
				</menuItem>
				<menuItem id="xSynthStockFI">
				<!-- KRA 64733 -->
					<filter_field not="true" fieldName="SousMenus" validValues="admbase"/>
				</menuItem>
				<menuItem id="xSynthFICompta">
				<!-- KRA 64733 -->
					<filter_field not="true" fieldName="SousMenus" validValues="admbase"/>
				</menuItem>
				<menuItem id="xStockImmo">
				<!-- KRA 64733 -->
					<filter_field not="true" fieldName="SousMenus" validValues="admbase"/>
				</menuItem>
				<menuItem id="xStockRA">
				<!-- KRA 64733 -->
					<filter_field not="true" fieldName="SousMenus" validValues="admbase"/>
				</menuItem>
				<menuItem id="xMultica">
				<!-- KRA 64733 -->
					<filter_field not="true" fieldName="SousMenus" validValues="admbase"/>
				</menuItem>
				<menuItem id="xHBudget">
				<!-- KRA 64733 -->
					<filter_field not="true" fieldName="SousMenus" validValues="admbase"/>
				</menuItem>
				<menuItem id="xConsoTableRepart">
				<!-- KRA 64733 -->
					<filter_field not="true" fieldName="SousMenus" validValues="admbase"/>
				</menuItem>
				<menuItem id="xRubriques">
				<!-- KRA 64733 -->
					<filter_field not="true" fieldName="SousMenus" validValues="admbase"/>
				</menuItem>
				<menuItem id="xSuiviFinancier">
				<!-- KRA 64733 -->
					<filter_field not="true" fieldName="SousMenus" validValues="admbase"/>
				</menuItem>
				<menuItem id="xSuiviFinancierKe">
				<!-- KRA 64733 -->
					<filter_field not="true" fieldName="SousMenus" validValues="admbase"/>
				</menuItem>
				<menuItem id="xSoussysteme">
				<!-- KRA 64733 -->
					<filter_field not="true" fieldName="SousMenus" validValues="admbase"/>
				</menuItem>
				<menuItem id="xDomaine">
				<!-- KRA 64733 -->
					<filter_field not="true" fieldName="SousMenus" validValues="admbase"/>
				</menuItem>
				<menuItem id="xBloc">
				<!-- KRA 64733 -->
					<filter_field not="true" fieldName="SousMenus" validValues="admbase"/>
				</menuItem>
				<menuItem id="xNPSI">
				<!-- KRA 64733 -->
					<filter_field not="true" fieldName="SousMenus" validValues="admbase"/>
				</menuItem>
			</menuItem>
			<menuItem id="Compta">
				<filter_field fieldName="SousMenus" validValues="admin" />
				<menuItem id="eFacintg" />
				<menuItem id="majStatut" />
				<menuItem id="eDetailBIP" />
				<menuItem id="xAuditImmo" />
				<menuItem id="xSynthImmo" />
				<menuItem id="xAnaImmo" />
				<menuItem id="majAuditImmo" />
				<menuItem id="xAuditCompta" />
				<menuItem id="eRubriquesAd" />
			</menuItem>
			<menuItem id="Exploitation">
				<filter_field fieldName="SousMenus" validValues="admin" />
				<menuItem id="consultCalendrier" />
				<menuItem id="majCalendrier" />
				<menuItem id="majParametresBIP" />
				<menuItem id="ssEdStat">
					<menuItem id="eStatEdTotEtat" />
					<menuItem id="eStatEdTotUser" />
					<menuItem id="eStatEdUser" />
				</menuItem>
			</menuItem>
			<menuItem id="Historique">
				<filter_field fieldName="SousMenus" validValues="admin" />
				<menuItem id="eHRess" />
				<menuItem id="eHLigneBIP" />
				<menuItem id="eHClientME" />
				<menuItem id="eHClientMO" />
				<menuItem id="eHDetailLigne" />
				<menuItem id="eHBudget" />
			</menuItem>
			<menuItem id="Surveillance">
				<filter_field fieldName="SousMenus" validValues="admin" />
				<menuItem id="Tracabilite">
					<filter_field fieldName="SousMenus" validValues="admin" />
					<menuItem id="consultLogsParamBip" />
					<menuItem id="consultLogsModeContractual" />
					<menuItem id="consultLogsCodePrestation" />
					<menuItem id="consultLogsDpg" />
					<menuItem id="consultLogsCoutStd" />
					<menuItem id="consultLogsCoutStdKE" />
					<menuItem id="consultLogLigneBIP" />
					<menuItem id="consultLogNotif" />
					<menuItem id="consultLogRessources" />
					<menuItem id="consultLogsApplication" />
					<menuItem id="consultLogsProjet" />
					<menuItem id="consultLogsDossierProjet" />
					<menuItem id="consultLogsDossierProjetCopi" />
					<menuItem id="consultLogContrats" />
					<menuItem id="consultLogsFacture" />
				</menuItem>
				<menuItem id="eRess0" />
				<menuItem id="eLignesCloses" />
				<menuItem id="xSSTache" />
				<menuItem id="xSSTacheRess" />
				<menuItem id="eSuiviJH" />
				<menuItem id="consultRBIP" />
				<menuItem id="consultLogsBip" />
				<!-- TD 532 -->
				<menuItem id="remiseZeroLigneBip" />
				<menuItem id="xVerifRTFE" />
				<menuItem id="xSurvSst" />
				<menuItem id="xSurConnexion" />
				<!-- YNI FDT 876 -->
				<menuItem id="consultPerimsRestit" />
				<!-- Fin YNI FDT 876 -->
				<menuItem id="consultControleCa" />
			</menuItem>
			<!--menuItem id="Traitbatch">
				<filter_field fieldName="SousMenus" validValues="admin" />
				<menuItem id="shell" />
				<menuItem id="upload" />
				<menuItem id="planifbatch" />
			</menuItem-->
			<menuItem id="PriseEnChargeISAC">
				<filter_field fieldName="SousMenus" validValues="admin" />					
			</menuItem>
			<menuItem id="BoiteOutils">
				<filter_or>
				<filter_field fieldName="SousMenus" validValues="admin" />
				<filter_field fieldName="SousMenus" validValues="admbase" />
				</filter_or>
			<!-- PPM 65058 -->
				<menuItem id="consultCRMens">	
				<!-- PPM 65058 -->
					<filter_or>
				<filter_field fieldName="SousMenus" validValues="admin" />
				<filter_field not="true" fieldName="SousMenus" validValues="admbase" />
				</filter_or>
				</menuItem>			
				<menuItem id="Paramsession">
				<!-- PPM 65058 -->
					<filter_or>
				<filter_field fieldName="SousMenus" validValues="admin" />
				<filter_field not="true" fieldName="SousMenus" validValues="admbase" />
				</filter_or>
				</menuItem>
				<menuItem id="ChargerProfil">
				<!-- PPM 65058 -->
					<filter_or>
				<filter_field fieldName="SousMenus" validValues="admin" />
				<filter_field not="true" fieldName="SousMenus" validValues="admbase" />
				</filter_or>
				</menuItem>
				<menuItem id="eStructLigneBIP" />
				<menuItem id="eVisuLigne" />
				<menuItem id="eMonProfil" />
				<menuItem id="eProfilsListeRessources">
				<!-- PPM 65058 -->
					<filter_or>
				<filter_field fieldName="SousMenus" validValues="admin" />
				<filter_field not="true" fieldName="SousMenus" validValues="admbase" />
				</filter_or>
				</menuItem>
				<menuItem id="eProfilCp">
				<!-- PPM 65058 -->
					<filter_or>
				<filter_field fieldName="SousMenus" validValues="admin" />
				<filter_field not="true" fieldName="SousMenus" validValues="admbase" />
				</filter_or>
				</menuItem>
				<!-- BIP 509 Hierarchy  -->
				<menuItem id="xRessHierarchy"/>
				<menuItem id="eProfilRess">
				<!-- PPM 65058 -->
					<filter_or>
				<filter_field fieldName="SousMenus" validValues="admin" />
				<filter_field not="true" fieldName="SousMenus" validValues="admbase" />
				</filter_or>
				</menuItem>
				<menuItem id="majMail">
				<!-- PPM 65058 -->
					<filter_or>
				<filter_field fieldName="SousMenus" validValues="admin" />
				<filter_field not="true" fieldName="SousMenus" validValues="admbase" />
				</filter_or>
				</menuItem>
				<menuItem id="xLibStat">
				<!-- PPM 65058 -->
					<filter_or>
				<filter_field fieldName="SousMenus" validValues="admin" />
				<filter_field not="true" fieldName="SousMenus" validValues="admbase" />
				</filter_or>
				</menuItem>
				
				<menuItem id="traitBatch">
				<!-- PPM 65058 -->
				<filter_or>
					<filter_field fieldName="SousMenus" validValues="admin" />
				<filter_field not="true" fieldName="SousMenus" validValues="admbase" />
				</filter_or>
				</menuItem>
				
				<menuItem id="eAdminLocaux">
				<!-- PPM 65058 -->
				<filter_or>
					<filter_field fieldName="SousMenus" validValues="admin" />
				<filter_field not="true" fieldName="SousMenus" validValues="admbase" />
				</filter_or>
				</menuItem>
				<menuItem id="uploadMens">
				<!-- PPM 65058 -->
				<filter_or>
					<filter_field fieldName="SousMenus" validValues="admin" />
				<filter_field not="true" fieldName="SousMenus"  validValues="admbase" />
				</filter_or>
				</menuItem>
				<!-- menuItem id="Forum">
					<menuItem id="forumMesMsg"/>
					<menuItem id="forumListe"/>
					<menuItem id="forumRecherche"/>
					<menuItem id="forumMsgAValider"/>	
					<menuItem id="forumMsgRejeter"/>	
					</menuItem-->
			</menuItem>
			<menuItem id="majActualites">
				<filter_field fieldName="SousMenus" validValues="admin" />
			</menuItem>
			<menuItem id="TraitDifferes" />
		</menu>

	    <!-- BIP 173 changes -->
	    <menu id="GENERAL">
	    	<menuItem id="Favoris" />
			<menuItem id="Table">
	    		<menuItem id="eTableDPG" />
				<menuItem id="eTableClients" />
				<menuItem id="eTableSocietes" />
				<menuItem id="eTablePrestations" />
				<menuItem id="eModeContractuel" />
				<menuItem id="eTableImmeubles" />
				<menuItem id="eTableTypesProjet" />
				<menuItem id="eTableCompta" />
				<menuItem id="eTableProjets" />
				<menuItem id="eTableApplications" />
				<menuItem id="eTableDossiersProjet" />
				<menuItem id="eTableCentre2Frais" />
				<menuItem id="eTableInvestissements" />
			</menuItem>
			<menuItem id="Referentiels">
				<menuItem id="ssEdRef">
					<menuItem id="eRef" />
					<menuItem id="eRefProj" />
					<menuItem id="ePCA4" />
					<menuItem id="eSuiviType1" />
					<menuItem id="eSuiviMOProj" />
					<menuItem id="eSuiviMOAppli" />
					<menuItem id="eSuiviMOProjSynth" />
					<menuItem id="eP9000" />
					<menuItem id="eProjetsSpeciaux" />
					<menuItem id="eDossierMultiMO" />
				</menuItem>
				<menuItem id="eRecherche" />
			</menuItem>
			<menuItem id="Export">
				<menuItem id="xLigneBip"/>
				<menuItem id="xDemandeLigneBip"/>
	    		<menuItem id="xDPG"/>
	    		<menuItem id="xSSTacheRessPublic"/>
	    	</menuItem>
	    	<menuItem id="BoiteOutils">
	    		<menuItem id="consultCRMens" />
	    		<menuItem id="eStructLigneBIP" />
	    		<menuItem id="eVisuLigne" />
				<menuItem id="consultLogLigneBIP" />
				<menuItem id="consultCalendrier" />
				<menuItem id="eMonProfil" />
				<menuItem id="eProfilsListeRessourcesNew" >
				<filter_field fieldName="SousMenus" validValues="suivbase"/>
				</menuItem>
				<!-- BIP 509 Hierarchy  -->
				<menuItem id="xRessHierarchy" />
				<menuItem id="documentionReferenceBIP" />
			</menuItem>
			<menuItem id="TraitDifferes" />
			
	    </menu>

		<!--	Menu Maitrise d'oeuvre -->

		<menu id="ME">
			<menuInfo id="infoSousMenu" />
			<menuInfo id="infoDPG" />
			<menuItem id="Favoris" />
			<menuItem id="Table">
				<menuItem id="eTableDPG" />
				<menuItem id="eTableClients" />
				<menuItem id="eTableSocietes" />
				<menuItem id="eTablePrestations" />
				<menuItem id="eModeContractuel" />
				<menuItem id="eTableStandards">
					<filter_field fieldName="SousMenus" validValues="ges"/>
				</menuItem>
				<menuItem id="eProfilsFi">
					<filter_field fieldName="SousMenus" validValues="ges"/>
				</menuItem>
				<!-- New Edition report for Profile localize - Starts -->
				<menuItem id="eProfilsLocalize" >
					<filter_field fieldName="SousMenus" validValues="ges"/>
				</menuItem>
					<!-- New Edition report for Profile localize - Ends -->
				<menuItem id="eProfilsDomFoncLong">
					<filter_field fieldName="SousMenus" validValues="ges"/>
				</menuItem>
				<menuItem id="eTableCoutMoyenComplet">
					<filter_field fieldName="SousMenus"
						validValues="ges" />
				</menuItem>
				<menuItem id="eTableImmeubles" />
				<menuItem id="eTableTypesProjet" />
				<menuItem id="eTableCompta" />
				<menuItem id="eTableProjets" />
				<menuItem id="eTableApplications" />
				<menuItem id="eTableDossiersProjet" />
				<menuItem id="eTableCentre2Frais" />
				<menuItem id="eTableInvestissements" />
				<!-- Test evolution 1234 -->
				<!--  <menuItem id="consulModify" />-->
			</menuItem>
			<menuItem id="Referentiels">
				<!-- FAD PPM 63547 : Début -->
				<filter_or>
					<!-- FAD PPM 63956 : Ajout du sous menu suivbase -->
					<filter_field fieldName="SousMenus" validValues="ges pcm bud suivbase"/>
					<!-- FAD PPM 63956 : Fin -->
					<filter_field not="true" fieldName="SousMenus" validValues="bubase"/>
				</filter_or>
				<!-- FAD PPM 63547 : Fin -->
				<menuItem id="ssEdRef">
					<menuItem id="eRef" />
					<menuItem id="eRefProj" />
					<menuItem id="ePCA4" />
					<menuItem id="eSuiviType1" />
					<menuItem id="eSuiviMOProj" />
					<menuItem id="eSuiviMOAppli" />
					<menuItem id="eSuiviMOProjSynth" />
					<menuItem id="eP9000" />
					<menuItem id="eProjetsSpeciaux" />
					<menuItem id="eDossierMultiMO" />
				</menuItem>
				<!-- FAD PPM 63988 : Suppression des menus "Recherche(chaîne)" et "Recherche(alpha)" et création du menu "Recherche" -->
				<menuItem id="eRecherche" />
				<!-- FAD PPM 63988 : Fin -->
			</menuItem>
			<menuItem id="Ressources">
				<!-- FAD PPM 63547 : Début -->
				<filter_or>
					<filter_field fieldName="SousMenus" validValues="ges pcm bud"/>
					<!-- FAD PPM 63956 : Ajout du sous menu suivbase -->
					<filter_field not="true" fieldName="SousMenus" validValues="bubase suivbase"/>
					<!-- FAD PPM 63956 : Fin -->
				</filter_or>
				<!-- FAD PPM 63547 : Fin -->
				<menuItem id="ssEdRess">
					<menuItem id="eRessources" />
					<menuItem id="eListeTel" />
					<menuItem id="eSuiviSSII" />
					<menuItem id="eSuiviPrestations" />
					<menuItem id="eContratsEchus" />
					<menuItem id="eRessOrdreAlpha" />
					<menuItem id="eRessCodeRess" />
					<!--  menuItem id="eOrganisation" -->
					<!--    filter_field fieldName="SousMenus" validValues="bud pcm ges"/ -->
					<!-- menuItem-->
					<menuItem id="eDetailAbsSG" />
					<menuItem id="eSyntheseAbsSG" />
					 <menuItem id="eContratRF" />  <!-- PPM_59805 -->
					<menuItem id="eEchangePac">
						<filter_field fieldName="SousMenus" validValues="ges pcm"/>
					</menuItem>
					<!-- ABN - HP PPM 57714 - DEBUT -->
					<!-- <menuItem id="eEchangeOalia">
						<filter_field fieldName="SousMenus" validValues="ges pcm"/>
					</menuItem> -->
					<!-- ABN - HP PPM 57714 - FIN -->
					<menuItem id="eEcarts">
					         <filter_field fieldName="SousMenus" validValues="pcm ges"/>
					</menuItem>



				</menuItem>
				<menuItem id="Consultation" />
				<!-- menuItem id="detailMe"/>
					<menuItem id="Consultation">
					<filter_field not="true" fieldName="SousMenus" validValues="pcm ges"/>
					<menuItem id="consultAgentSG"/>
					<menuItem id="consultPrestation"/>
					<menuItem id="consultLogiciel"/>
					<menuItem id="consultForfait"/>
					</menuItem-->
				<menuItem id="ssMAJRess">
					<filter_field fieldName="SousMenus"
						validValues="pcm ges" />
					<menuItem id="majAgentSG" />
					<menuItem id="majPrestataires" />
					<menuItem id="majLogiciels" />
					<menuItem id="majForfaits" />
				</menuItem>
				<menuItem id="ssBouclageRess">
					<menuItem id="bjhValidErreurs">
						<filter_field fieldName="SousMenus"
							validValues="pcm ges" />
					</menuItem>
					<menuItem id="eBjh" />
				</menuItem>
				<menuItem id="majEcarts">
					<filter_field fieldName="SousMenus"
						validValues="pcm ges" />
				</menuItem>
				<menuItem id="eSyntheseGlobaleMe" />
			</menuItem>